// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CronJobsColumns holds the columns for the "cron_jobs" table.
	CronJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "cron", Type: field.TypeString},
		{Name: "entry_id", Type: field.TypeInt},
		{Name: "prev", Type: field.TypeInt64},
		{Name: "next", Type: field.TypeInt64},
	}
	// CronJobsTable holds the schema information for the "cron_jobs" table.
	CronJobsTable = &schema.Table{
		Name:       "cron_jobs",
		Columns:    CronJobsColumns,
		PrimaryKey: []*schema.Column{CronJobsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Comment:    "user info table",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CronJobsTable,
		UsersTable,
	}
)

func init() {
	UsersTable.Annotation = &entsql.Annotation{}
}
