// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CronJob is the predicate function for cronjob builders.
type CronJob func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
