// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ginx-contribs/ginx-server/server/data/ent/cronjob"
	"github.com/ginx-contribs/ginx-server/server/data/ent/predicate"
)

// CronJobUpdate is the builder for updating CronJob entities.
type CronJobUpdate struct {
	config
	hooks     []Hook
	mutation  *CronJobMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CronJobUpdate builder.
func (cju *CronJobUpdate) Where(ps ...predicate.CronJob) *CronJobUpdate {
	cju.mutation.Where(ps...)
	return cju
}

// SetName sets the "name" field.
func (cju *CronJobUpdate) SetName(s string) *CronJobUpdate {
	cju.mutation.SetName(s)
	return cju
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cju *CronJobUpdate) SetNillableName(s *string) *CronJobUpdate {
	if s != nil {
		cju.SetName(*s)
	}
	return cju
}

// SetCron sets the "cron" field.
func (cju *CronJobUpdate) SetCron(s string) *CronJobUpdate {
	cju.mutation.SetCron(s)
	return cju
}

// SetNillableCron sets the "cron" field if the given value is not nil.
func (cju *CronJobUpdate) SetNillableCron(s *string) *CronJobUpdate {
	if s != nil {
		cju.SetCron(*s)
	}
	return cju
}

// SetEntryID sets the "entry_id" field.
func (cju *CronJobUpdate) SetEntryID(i int) *CronJobUpdate {
	cju.mutation.ResetEntryID()
	cju.mutation.SetEntryID(i)
	return cju
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (cju *CronJobUpdate) SetNillableEntryID(i *int) *CronJobUpdate {
	if i != nil {
		cju.SetEntryID(*i)
	}
	return cju
}

// AddEntryID adds i to the "entry_id" field.
func (cju *CronJobUpdate) AddEntryID(i int) *CronJobUpdate {
	cju.mutation.AddEntryID(i)
	return cju
}

// SetPrev sets the "prev" field.
func (cju *CronJobUpdate) SetPrev(i int64) *CronJobUpdate {
	cju.mutation.ResetPrev()
	cju.mutation.SetPrev(i)
	return cju
}

// SetNillablePrev sets the "prev" field if the given value is not nil.
func (cju *CronJobUpdate) SetNillablePrev(i *int64) *CronJobUpdate {
	if i != nil {
		cju.SetPrev(*i)
	}
	return cju
}

// AddPrev adds i to the "prev" field.
func (cju *CronJobUpdate) AddPrev(i int64) *CronJobUpdate {
	cju.mutation.AddPrev(i)
	return cju
}

// SetNext sets the "next" field.
func (cju *CronJobUpdate) SetNext(i int64) *CronJobUpdate {
	cju.mutation.ResetNext()
	cju.mutation.SetNext(i)
	return cju
}

// SetNillableNext sets the "next" field if the given value is not nil.
func (cju *CronJobUpdate) SetNillableNext(i *int64) *CronJobUpdate {
	if i != nil {
		cju.SetNext(*i)
	}
	return cju
}

// AddNext adds i to the "next" field.
func (cju *CronJobUpdate) AddNext(i int64) *CronJobUpdate {
	cju.mutation.AddNext(i)
	return cju
}

// Mutation returns the CronJobMutation object of the builder.
func (cju *CronJobUpdate) Mutation() *CronJobMutation {
	return cju.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cju *CronJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cju.sqlSave, cju.mutation, cju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cju *CronJobUpdate) SaveX(ctx context.Context) int {
	affected, err := cju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cju *CronJobUpdate) Exec(ctx context.Context) error {
	_, err := cju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cju *CronJobUpdate) ExecX(ctx context.Context) {
	if err := cju.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (cju *CronJobUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CronJobUpdate {
	cju.modifiers = append(cju.modifiers, modifiers...)
	return cju
}

func (cju *CronJobUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cronjob.Table, cronjob.Columns, sqlgraph.NewFieldSpec(cronjob.FieldID, field.TypeInt))
	if ps := cju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cju.mutation.Name(); ok {
		_spec.SetField(cronjob.FieldName, field.TypeString, value)
	}
	if value, ok := cju.mutation.Cron(); ok {
		_spec.SetField(cronjob.FieldCron, field.TypeString, value)
	}
	if value, ok := cju.mutation.EntryID(); ok {
		_spec.SetField(cronjob.FieldEntryID, field.TypeInt, value)
	}
	if value, ok := cju.mutation.AddedEntryID(); ok {
		_spec.AddField(cronjob.FieldEntryID, field.TypeInt, value)
	}
	if value, ok := cju.mutation.Prev(); ok {
		_spec.SetField(cronjob.FieldPrev, field.TypeInt64, value)
	}
	if value, ok := cju.mutation.AddedPrev(); ok {
		_spec.AddField(cronjob.FieldPrev, field.TypeInt64, value)
	}
	if value, ok := cju.mutation.Next(); ok {
		_spec.SetField(cronjob.FieldNext, field.TypeInt64, value)
	}
	if value, ok := cju.mutation.AddedNext(); ok {
		_spec.AddField(cronjob.FieldNext, field.TypeInt64, value)
	}
	_spec.AddModifiers(cju.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, cju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cronjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cju.mutation.done = true
	return n, nil
}

// CronJobUpdateOne is the builder for updating a single CronJob entity.
type CronJobUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CronJobMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (cjuo *CronJobUpdateOne) SetName(s string) *CronJobUpdateOne {
	cjuo.mutation.SetName(s)
	return cjuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cjuo *CronJobUpdateOne) SetNillableName(s *string) *CronJobUpdateOne {
	if s != nil {
		cjuo.SetName(*s)
	}
	return cjuo
}

// SetCron sets the "cron" field.
func (cjuo *CronJobUpdateOne) SetCron(s string) *CronJobUpdateOne {
	cjuo.mutation.SetCron(s)
	return cjuo
}

// SetNillableCron sets the "cron" field if the given value is not nil.
func (cjuo *CronJobUpdateOne) SetNillableCron(s *string) *CronJobUpdateOne {
	if s != nil {
		cjuo.SetCron(*s)
	}
	return cjuo
}

// SetEntryID sets the "entry_id" field.
func (cjuo *CronJobUpdateOne) SetEntryID(i int) *CronJobUpdateOne {
	cjuo.mutation.ResetEntryID()
	cjuo.mutation.SetEntryID(i)
	return cjuo
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (cjuo *CronJobUpdateOne) SetNillableEntryID(i *int) *CronJobUpdateOne {
	if i != nil {
		cjuo.SetEntryID(*i)
	}
	return cjuo
}

// AddEntryID adds i to the "entry_id" field.
func (cjuo *CronJobUpdateOne) AddEntryID(i int) *CronJobUpdateOne {
	cjuo.mutation.AddEntryID(i)
	return cjuo
}

// SetPrev sets the "prev" field.
func (cjuo *CronJobUpdateOne) SetPrev(i int64) *CronJobUpdateOne {
	cjuo.mutation.ResetPrev()
	cjuo.mutation.SetPrev(i)
	return cjuo
}

// SetNillablePrev sets the "prev" field if the given value is not nil.
func (cjuo *CronJobUpdateOne) SetNillablePrev(i *int64) *CronJobUpdateOne {
	if i != nil {
		cjuo.SetPrev(*i)
	}
	return cjuo
}

// AddPrev adds i to the "prev" field.
func (cjuo *CronJobUpdateOne) AddPrev(i int64) *CronJobUpdateOne {
	cjuo.mutation.AddPrev(i)
	return cjuo
}

// SetNext sets the "next" field.
func (cjuo *CronJobUpdateOne) SetNext(i int64) *CronJobUpdateOne {
	cjuo.mutation.ResetNext()
	cjuo.mutation.SetNext(i)
	return cjuo
}

// SetNillableNext sets the "next" field if the given value is not nil.
func (cjuo *CronJobUpdateOne) SetNillableNext(i *int64) *CronJobUpdateOne {
	if i != nil {
		cjuo.SetNext(*i)
	}
	return cjuo
}

// AddNext adds i to the "next" field.
func (cjuo *CronJobUpdateOne) AddNext(i int64) *CronJobUpdateOne {
	cjuo.mutation.AddNext(i)
	return cjuo
}

// Mutation returns the CronJobMutation object of the builder.
func (cjuo *CronJobUpdateOne) Mutation() *CronJobMutation {
	return cjuo.mutation
}

// Where appends a list predicates to the CronJobUpdate builder.
func (cjuo *CronJobUpdateOne) Where(ps ...predicate.CronJob) *CronJobUpdateOne {
	cjuo.mutation.Where(ps...)
	return cjuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cjuo *CronJobUpdateOne) Select(field string, fields ...string) *CronJobUpdateOne {
	cjuo.fields = append([]string{field}, fields...)
	return cjuo
}

// Save executes the query and returns the updated CronJob entity.
func (cjuo *CronJobUpdateOne) Save(ctx context.Context) (*CronJob, error) {
	return withHooks(ctx, cjuo.sqlSave, cjuo.mutation, cjuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cjuo *CronJobUpdateOne) SaveX(ctx context.Context) *CronJob {
	node, err := cjuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cjuo *CronJobUpdateOne) Exec(ctx context.Context) error {
	_, err := cjuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cjuo *CronJobUpdateOne) ExecX(ctx context.Context) {
	if err := cjuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (cjuo *CronJobUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CronJobUpdateOne {
	cjuo.modifiers = append(cjuo.modifiers, modifiers...)
	return cjuo
}

func (cjuo *CronJobUpdateOne) sqlSave(ctx context.Context) (_node *CronJob, err error) {
	_spec := sqlgraph.NewUpdateSpec(cronjob.Table, cronjob.Columns, sqlgraph.NewFieldSpec(cronjob.FieldID, field.TypeInt))
	id, ok := cjuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CronJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cjuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cronjob.FieldID)
		for _, f := range fields {
			if !cronjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cronjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cjuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cjuo.mutation.Name(); ok {
		_spec.SetField(cronjob.FieldName, field.TypeString, value)
	}
	if value, ok := cjuo.mutation.Cron(); ok {
		_spec.SetField(cronjob.FieldCron, field.TypeString, value)
	}
	if value, ok := cjuo.mutation.EntryID(); ok {
		_spec.SetField(cronjob.FieldEntryID, field.TypeInt, value)
	}
	if value, ok := cjuo.mutation.AddedEntryID(); ok {
		_spec.AddField(cronjob.FieldEntryID, field.TypeInt, value)
	}
	if value, ok := cjuo.mutation.Prev(); ok {
		_spec.SetField(cronjob.FieldPrev, field.TypeInt64, value)
	}
	if value, ok := cjuo.mutation.AddedPrev(); ok {
		_spec.AddField(cronjob.FieldPrev, field.TypeInt64, value)
	}
	if value, ok := cjuo.mutation.Next(); ok {
		_spec.SetField(cronjob.FieldNext, field.TypeInt64, value)
	}
	if value, ok := cjuo.mutation.AddedNext(); ok {
		_spec.AddField(cronjob.FieldNext, field.TypeInt64, value)
	}
	_spec.AddModifiers(cjuo.modifiers...)
	_node = &CronJob{config: cjuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cjuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cronjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cjuo.mutation.done = true
	return _node, nil
}
