// Code generated by ent, DO NOT EDIT.

package ent

func (cjc *CronJobCreate) SetCronJob(input *CronJob) *CronJobCreate {
	cjc.SetName(input.Name)
	cjc.SetCron(input.Cron)
	cjc.SetEntryID(input.EntryID)
	cjc.SetPrev(input.Prev)
	cjc.SetNext(input.Next)
	return cjc
}

func (uc *UserCreate) SetUser(input *User) *UserCreate {
	uc.SetUID(input.UID)
	uc.SetUsername(input.Username)
	uc.SetEmail(input.Email)
	uc.SetPassword(input.Password)
	uc.SetCreatedAt(input.CreatedAt)
	uc.SetUpdatedAt(input.UpdatedAt)
	return uc
}
