// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/ginx-contribs/ginx-server/server/api"
	auth2 "github.com/ginx-contribs/ginx-server/server/api/auth"
	"github.com/ginx-contribs/ginx-server/server/api/system"
	user2 "github.com/ginx-contribs/ginx-server/server/api/user"
	"github.com/ginx-contribs/ginx-server/server/data/cache"
	"github.com/ginx-contribs/ginx-server/server/data/mq"
	"github.com/ginx-contribs/ginx-server/server/data/repo"
	"github.com/ginx-contribs/ginx-server/server/handler/auth"
	"github.com/ginx-contribs/ginx-server/server/handler/email"
	"github.com/ginx-contribs/ginx-server/server/handler/user"
	"github.com/ginx-contribs/ginx-server/server/svc"
	"github.com/ginx-contribs/ginx-server/server/types"
)

import (
	_ "github.com/ginx-contribs/ent-sqlite"
	_ "time/tzdata"
)

// Injectors from wire.go:

// initialize and setup app environment
func Setup(ctx types.Context) (svc.Context, error) {
	routerGroup := ctx.Router
	app := ctx.AppConf
	jwt := app.Jwt
	client := ctx.Redis
	tokenHandler := auth.NewTokenHandler(jwt, client)
	entClient := ctx.Ent
	userRepo := repo.NewUserRepo(entClient)
	redisCodeCache := cache.NewRedisCodeCache(client)
	confEmail := app.Email
	mailClient := ctx.Email
	streamQueue := mq.NewStreamQueue(client)
	handler, err := email.NewEmailHandler(confEmail, mailClient, streamQueue)
	if err != nil {
		return svc.Context{}, err
	}
	verifyCodeHandler := auth.NewVerifyCodeHandler(redisCodeCache, handler)
	authHandler := auth.NewAuthHandler(userRepo, tokenHandler, verifyCodeHandler)
	authAPI := auth2.NewAuthAPI(tokenHandler, authHandler, verifyCodeHandler)
	router := auth2.NewRouter(routerGroup, authAPI)
	systemAPI := system.NewSystemAPI()
	systemRouter := system.NewRouter(routerGroup, systemAPI)
	userHandler := user.NewUserHandler(userRepo)
	userAPI := user2.NewUserAPI(userHandler)
	userRouter := user2.NewRouter(routerGroup, userAPI)
	apiRouter := api.Router{
		Auth:   router,
		System: systemRouter,
		User:   userRouter,
	}
	context := svc.Context{
		ApiRouter:    apiRouter,
		UserHandler:  userHandler,
		UserRepo:     userRepo,
		AuthHandler:  authHandler,
		EmailHandler: handler,
		MQ:           streamQueue,
	}
	return context, nil
}
