package doc

// RegisterRouter
// @title	                        HTTP API
// @version		                    v0.0.0-Dev
// @description                     This is http api document generated by swagger.
// @contact.name                    ginx-contribs
// @contact.url                     https://github.com/ginx-contribs
// @BasePath	                    /api/
// @license.name                    MIT LICENSE
// @license.url                     https://mit-license.org/
// @securityDefinitions.apikey      BearerAuth
// @in                              header
// @name                            Authorization
//go:generate swag init --generatedTime -g swagger.go -d ./,../../ --output ./ && swag fmt -g swagger.go -d ./,../../
