// Code generated by ent, DO NOT EDIT.

package ent

func (uc *UserCreate) SetUser(input *User) *UserCreate {
	uc.SetUID(input.UID)
	uc.SetUsername(input.Username)
	uc.SetEmail(input.Email)
	uc.SetPassword(input.Password)
	uc.SetCreatedAt(input.CreatedAt)
	uc.SetUpdatedAt(input.UpdatedAt)
	return uc
}
